FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --root-user-action=ignore requests --upgrade pip
RUN pip install --root-user-action=ignore requests --no-cache-dir -r requirements.txt

COPY . .
RUN mkdir ./dockerdata
CMD [ "python", "./bot.py" ]
